title            : Codz by Marmotz
description      : Javascript, TypeScript, Angular & Electron
logo             : logo.png
disqus_shortname : marmotz-github-io
share            : true
dropcap          : true
# Change url to your domain. Leave localhost server or blank when working locally.
# or use the hint from http://jekyllrb.com/docs/github-pages/ to keep this the same
# whether working locally or remotely. Start Jekyll with: jekyll serve --baseurl ''
url: "https://marmotz.github.io"
url: "http://localhost:4000"

# Owner/author information
owner:
  name        : marmotz
  avatar      : avatar.jpg
  email       : rlittolff@gmail.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description : Passionn&#233; de dev depuis mon plus jeune age, j&#39;ai d&#233;couvert le dev web &#224; ses d&#233;buts. J&#39;ai la chance de pouvoir en vivre.
  # Social networking links used in footer. Update and remove as you like.
  twitter     : marmotz
  # facebook:       hmfaysal
  github      : marmotz
  # instagram:      hmfaysal
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:    https://plus.google.com/u/0/102602916593522619858

# Analytics and webmaster tools stuff goes here
google_analytics : UA-85403815-1
google_verify    :
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify      :

# Links to include in footer navigation
# For external links add external: true
links:
  - title : Accueil
    url   : /
    icon  : home
  # - title: Featured Posts
  #   url: /featured
  - title : Tags
    url   : /tags
    icon  : tags
  # - title: About
  #   url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone      : Europe/Paris
future        : false
show_drafts   : true
highlighter   : rouge
markdown      : kramdown
paginate      : 5
paginate_path : "page:num"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink : /:year/:month/:day/:title

kramdown:
  input          : GFM
  auto_ids       : true
  footnote_nr    : 1
  entity_output  : as_char
  toc_levels     : 1..6
  enable_coderay : false

  coderay:
    coderay_line_numbers       :
    coderay_line_numbers_start : 1
    coderay_tab_width          : 4
    coderay_bold_every         : 10
    coderay_css                : class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

jekyll-archives:
  enabled: [ year, month, day ]
  layouts:
    year  : year
    month : month
    day   : day
  permalinks:
    year  : '/:year/'
    month : '/:year/:month/'
    day   : '/:year/:month/:day/'

gems:
  - jekyll-paginate
  - jekyll-archives
